### ISSUE TITLE
Import / export does not support dialects properly

### ISSUE THREAD

**Issue by robcharlwood** [potatolondon/fluent-2.0#23]
Import and export functionality does not correctly support dialects like the rest of the codebase does. If you pass ``pt-br`` into the export or import methods, it explodes. This is because the code in ``cldr.rules`` is not dialect aware and only supports base languages e.g ``pt``.

**Comment by davidwtbuxton** [comment]
Traceback when trying to export translations for "pt-br" locale:

```
ERROR Internal Server Error: /translations/export/pt-br/
Traceback (most recent call last):
  File "/Users/jeff/myproject/sitepackages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jeff/myproject/core/decorators.py", line 13, in wrap
    return func(request, *args, **kwargs)
  File "/Users/jeff/myproject/views.py", line 973, in translations_export
    return export_translations_to_po(language_code)
  File "/Users/jeff/myproject/sitepackages/fluent/importexport.py", line 208, in export_translations_to_po
    lookup = LANGUAGE_LOOKUPS[language_code]
KeyError: u'pt-br'
```


The view function that calls `export_translations_to_po`:

```
from fluent.importexport import export_translations_to_po

def translations_export(request, language_code=None):
    if language_code:
        return export_translations_to_po(language_code)
    else:
        return render(request, "export.html", {
            'languages': settings.LANGUAGES,
        })
```

Happens with current HEAD of fluent, commit bbcbb497f0c52b09f86365785b30b9b481ff89dc .
